remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  
author:
  name: "Stefan Alpers"
  location: "Oberhausen, Germany"
  email: "stefan.alpers@gmx.net"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-square-envelope"
description: ""
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/stefanalpers"
name: "Stefan Alpers"
show_date: true
title: "Stefan's thoughts about issues of all kinds"