remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: "Stefan's thoughts about issues of all kinds"
name: "Stefan Alpers"
description: ""
show_date: true
show_tags: true

author:
  name: "Stefan Alpers"
  location: "Oberhausen, Germany"
  email: "stefan.alpers@gmx.net"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-square-envelope"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/stefanalpers"

tag_archive:
  type: liquid
  path: /tags/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true